NAMES	=	server
NAMEC	=	client

SRCS	=	dserver/main.c\
		dserver/handle_signal.c\
		dserver/set_path.c\
		dserver/manage_cmd.c\
		dserver/adduser.c\
		dserver/connection.c\
		dserver/get_message.c\
		dserver/init.c\
		dserver/my_cd.c\
		dserver/my_pwd.c\
		dserver/my_ls.c\
		dserver/my_logout.c\
		dserver/my_put.c\
		dserver/my_get.c\
		dserver/get_passwd_file.c\
		dserver/no_file.c\
		dserver/transfer.c\
		func/my_totab.c\
		func/my_exit.c\
		func/xwrite.c

SRCC	=	dclient/main.c\
		dclient/handle_signal.c\
		dclient/adduser.c\
		dclient/my_lls.c\
		dclient/my_lpwd.c\
		dclient/handle_user.c\
		dclient/handle_cmd.c\
		dclient/init.c\
		dclient/my_cd.c\
		dclient/my_ls.c\
		dclient/my_logout.c\
		dclient/my_get.c\
		dclient/my_put.c\
		dclient/my_pwd.c\
		dclient/puts.c\
		dclient/no_file.c\
		dclient/transfer.c\
		dclient/local.c\
		func/my_totab.c\
		func/my_exit.c\
		func/xwrite.c

OBJS	=	$(SRCS:.c=.o)
OBJC	=	$(SRCC:.c=.o)

CFLAGS	=	-g

all:		$(NAMES) $(NAMEC)

$(NAMES):	$(OBJS) $(OBJC)
		cc -o $(NAMES) $(OBJS) -lpthread
		cc -o $(NAMEC) $(OBJC)

clean:
	rm -f $(OBJS) $(OBJC)

fclean:	clean
	rm -f $(NAMES) $(NAMEC)

re:	fclean all
NAMES	=	server
NAMEC	=	client

SRCS	=	dserver/main.c\
		dserver/handle_signal.c\
		dserver/set_path.c\
		dserver/manage_cmd.c\
		dserver/adduser.c\
		dserver/connection.c\
		dserver/get_message.c\
		dserver/init.c\
		dserver/my_cd.c\
		dserver/my_pwd.c\
		dserver/my_ls.c\
		dserver/my_logout.c\
		dserver/my_put.c\
		dserver/my_get.c\
		dserver/get_passwd_file.c\
		dserver/no_file.c\
		dserver/transfer.c\
		func/my_totab.c\
		func/my_exit.c\
		func/xwrite.c

SRCC	=	dclient/main.c\
		dclient/handle_signal.c\
		dclient/adduser.c\
		dclient/my_lls.c\
		dclient/my_lpwd.c\
		dclient/my_lcd.c\
		dclient/handle_user.c\
		dclient/handle_cmd.c\
		dclient/init.c\
		dclient/my_cd.c\
		dclient/my_ls.c\
		dclient/my_logout.c\
		dclient/my_get.c\
		dclient/my_put.c\
		dclient/my_pwd.c\
		dclient/puts.c\
		dclient/no_file.c\
		dclient/transfer.c\
		dclient/local.c\
		func/my_totab.c\
		func/my_exit.c\
		func/xwrite.c

OBJS	=	$(SRCS:.c=.o)
OBJC	=	$(SRCC:.c=.o)

CFLAGS	=	-g

all:		$(NAMES) $(NAMEC)

$(NAMES):	$(OBJS) $(OBJC)
		cc -o $(NAMES) $(OBJS) -lpthread
		cc -o $(NAMEC) $(OBJC)

clean:
	rm -f $(OBJS) $(OBJC)

fclean:	clean
	rm -f $(NAMES) $(NAMEC)

re:	fclean all
NAMES	=	server
NAMEC	=	client

SRCS	=	dserver/main.c\
		dserver/handle_signal.c\
		dserver/set_path.c\
		dserver/manage_cmd.c\
		dserver/adduser.c\
		dserver/connection.c\
		dserver/get_message.c\
		dserver/init.c\
		dserver/my_cd.c\
		dserver/my_pwd.c\
		dserver/my_ls.c\
		dserver/my_logout.c\
		dserver/my_put.c\
		dserver/my_get.c\
		dserver/get_passwd_file.c\
		dserver/no_file.c\
		dserver/transfer.c\
		func/my_totab.c\
		func/my_exit.c\
		func/xwrite.c

SRCC	=	dclient/main.c\
		dclient/handle_signal.c\
		dclient/adduser.c\
		dclient/my_lls.c\
		dclient/my_lpwd.c\
		dclient/my_lcd.c\
		dclient/handle_user.c\
		dclient/handle_cmd.c\
		dclient/init.c\
		dclient/my_cd.c\
		dclient/my_ls.c\
		dclient/my_logout.c\
		dclient/my_get.c\
		dclient/my_put.c\
		dclient/my_pwd.c\
		dclient/puts.c\
		dclient/no_file.c\
		dclient/transfer.c\
		dclient/local.c\
		func/my_totab.c\
		func/my_exit.c\
		func/xwrite.c

OBJS	=	$(SRCS:.c=.o)
OBJC	=	$(SRCC:.c=.o)

CFLAGS	=	-g

all:		$(NAMES) $(NAMEC)

$(NAMES):	$(OBJS) $(OBJC)
		cc -o $(NAMES) $(OBJS) -lpthread
		cc -o $(NAMEC) $(OBJC)

clean:
	rm -f $(OBJS) $(OBJC)

fclean:	clean
	rm -f $(NAMES) $(NAMEC)

re:	fclean all
